### ISSUE TITLE
Better WP-CLI updates

### ISSUE THREAD

**Issue by nyordanov** [wp-cli/wp-cli#1536]
- [x] Easy updates (#522, #1535)
- [x] WP_CLI_VERSION should not be in `php/wp-cli.php` (#680, https://github.com/wp-cli/wp-cli/pull/1535#issuecomment-65385232, #1539)
- [x] Automatic update checks #1011
- [x] Build checksums (#1199, #1555)
- [x] New version filters for `wp cli check-update` and support for major releases (#1390, https://github.com/wp-cli/wp-cli/pull/1535#discussion_r21221600, #1547)
- <del>[ ] Offer update instructions when installed via Composer/Git (https://github.com/wp-cli/wp-cli/pull/1535#discussion_r21234919)</del>

**Comment by danielbachhuber** [comment]
> Offer update instructions when installed via Composer/Git

@nyordanov Do you have any recommendations for this?

**Comment by nyordanov** [comment]
@danielbachhuber please see https://github.com/nyordanov/wp-cli/commit/e7610a62cd1fbe0a5e6b3d15fa270e1c1b92727e

We can detect Git installs by the presence of a .git directory. I'm not sure what is the correct way to detect if this is a Composer install.

**Comment by danielbachhuber** [comment]
Punting on the last item — Composer and Git installers can manage their own updates.
