### ISSUE TITLE
v0.23.0 Release Checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2542]
In addition to the standard release checklist, these are the additional steps we need to perform for releasing v0.23.0:

* [x] Add Docs and Package Index to the site header.
* [x] Update Package Index template to use the new header.
* [x] Reach out to maintainers of existing packages about updating their README, etc.
* [x] Update README.md to include new documentation references.

**Comment by danielbachhuber** [comment]
Did a bit of outreach
