### ISSUE TITLE
v0.24.0 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2767]
In addition to the [standard release checklist](http://wp-cli.org/docs/release-checklist/), these are the additional steps we need to perform for releasing v0.24.0, shortly prior to the release:

* [x] Document new `--ssh=<host>` configuration argument (#2754)
* [x] Document new aliases feature (#2309)
* [x] Ensure those who contributed documentation are mentioned in the contributor list
