### ISSUE TITLE
WP-CLI v1.2.0 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4046]
In addition to the [standard release checklist](http://wp-cli.org/docs/release-checklist/), these are the additional steps we need to perform for releasing v1.2.0:

* [x] Release scaffold-package command v0.3.0 (with improvements for bundled commands) https://github.com/wp-cli/scaffold-package-command/milestone/3
* [x] Regenerate `README.md` and update test suite for each bundled package.
* [x] Ensure outstanding versions of bundled packages are tagged.

**Comment by schlessera** [comment]
[ ] Dev-note about bootstrap refactoring.

**Comment by danielbachhuber** [comment]
It took me way longer than I expected, but all packages now have tagged releases.

**Comment by schlessera** [comment]
`wp-cli/package-command` might need an update: https://github.com/wp-cli/package-command/pull/16

**Comment by danielbachhuber** [comment]
🚢
