### ISSUE TITLE
WP-CLI v1.3.0 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4226]
In addition to the [standard release checklist](http://wp-cli.org/docs/release-checklist/), these are the additional steps we need to perform for releasing v1.3.0:

* [x] Close all issues in the handbook v1.3.0 milestone https://github.com/wp-cli/handbook/milestone/3
* [x] Tag releases on outstanding package milestones.
* [x] Add @jalavoy, @murtzsarialtun to contributor list (for work on RPM scripts)
* [x] Add @JPry, @pierre-dargham for their work on Composer tests.
* [x] Add @mapk to contributor list (for design contributions)

**Comment by danielbachhuber** [comment]
@wp-cli/committers I'm thinking about an August 9th release date for v1.3.0. Any opinions in opposition, or does this seem reasonable?

**Comment by schlessera** [comment]
Seems reasonable. Let's go through the milestone this evening to decide what we want to include.

**Comment by danielbachhuber** [comment]
@wp-cli/committers Tagged releases for all current versions on bundled packages. At this point, let's refrain from merging anything but critical bug fixes until after release.

**Comment by danielbachhuber** [comment]
> I'm thinking about an August 9th release date for v1.3.0

Off by a day, whoops.

🚢
