### ISSUE TITLE
WP-CLI v1.4.1 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4496]
In addition to the [standard release checklist](http://wp-cli.org/docs/release-checklist/), these are the additional steps we need to perform for releasing v1.4.1:

* [x] Cherry-pick the fix for https://github.com/wp-cli/package-command/issues/44 on to the appropriate standalone release.
* [x] Cherry-pick the fix for https://github.com/wp-cli/search-replace-command/issues/42 onto the appropriate standalone release.
* [x] Cherry-pick the fix for https://github.com/wp-cli/extension-command/issues/60 onto the appropriate standalone release.
* [x] Create a release branch.
* [x] Build the distributed Phar locally and have @schlessera verify.
* [x] Update release checklist documentation to communicate steps associated with bundled commands.

**Comment by danielbachhuber** [comment]
@schlessera Heads up ^ that there are three bugs I think we need to address in v1.4.1

**Comment by danielbachhuber** [comment]
🔨
