### ISSUE TITLE
WP-CLI v1.5.0 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4512]
In addition to the [standard release checklist](http://wp-cli.org/docs/release-checklist/), these are the additional steps we need to perform for releasing v1.5.0:

* [x] Document `longdesc` argument from #4513 in Commands Cookbook
* [x] Add @swissspidy to credit list for work on wp-cli/embed-command
* [x] Add checksum project contributors to credit list for their work
* [x] Fix https://github.com/wp-cli/db-command/issues/74
* [x] Fix https://github.com/wp-cli/media-command/issues/60
* [x] Merge https://github.com/wp-cli/package-command/pull/60
* [x] Implement https://github.com/wp-cli/config-command/issues/41
* [x] Include https://github.com/wp-cli/wp-config-transformer/pull/1
* [ ] ~Fix https://github.com/wp-cli/scaffold-command/issues/109~ Removing as incomplete

**Comment by gitlost** [comment]
Okay so here's the packages that have changes and need releasing that I can see:

* [x] "wp-cli/checksum-command": "^1.0", needs release 1.0.7
* [ ] "wp-cli/config-command": "^1.0", needs release 1.1.8
* [ ] "wp-cli/core-command": "^1.0", needs release 1.0.9
* [ ] "wp-cli/db-command": "^1.0", needs release 1.3.3
* [ ] "wp-cli/entity-command": "^1.0", needs release 1.2.0, 1 milestone issue open
* [ ] "wp-cli/export-command": "^1.0", needs release 1.0.6
* [ ] "wp-cli/extension-command": "^1.0", needs release 1.1.9, outstanding bug
* [ ] "wp-cli/media-command": "^1.0", needs release 1.1.4
* [ ] "wp-cli/package-command": "^1.0", needs release 1.0.11
* [ ] "wp-cli/scaffold-command": "^1.0", needs release 1.1.2
* [ ] "wp-cli/search-replace-command": "^1.0", needs release 1.1.5
* [ ] "wp-cli/handbook": "^1.0", needs release 1.5.0

**Comment by danielbachhuber** [comment]
> Okay so here's the packages that have changes and need releasing that I can see:

See also: https://make.wordpress.org/cli/dash/

![image](https://user-images.githubusercontent.com/36432/35517616-d63abc4e-04c3-11e8-841a-6c6c01c1e65a.png)

I think `checksum-command` still shows up there because the milestone wasn't closed.

**Comment by schlessera** [comment]
Working on releasing `wp-cli/core-command` now, after I've fixed the tests.

**Comment by gitlost** [comment]
Seems to be a time delay with the dash - checksum was closed 30 odd minutes ago and just closed embed and no change...

**Comment by danielbachhuber** [comment]
> Seems to be a time delay with the dash - checksum was closed 30 odd minutes ago and just closed embed and no change...

Yes, there's caching.

**Comment by schlessera** [comment]
While `core-command` is running its tests, working on releasing `wp-cli/search-replace-command`.

**Comment by schlessera** [comment]
Changing milestone for `wp-cli/search-replace-command` from `v1.1.5` to `v1.2.0`m because of the change in table output (now sorted).

**Comment by gitlost** [comment]
Thanks @grappler, so there doesn't seem to be a solution currently?

If possible could you raise an issue about it when you have the time on https://github.com/wp-cli/scaffold-command/issues

**Comment by grappler** [comment]
@gitlost The temp solution today would be to remove the text domain. Once there is a correct way of adding the text domain that could be added in a future release... 

I have created an issue. https://github.com/wp-cli/scaffold-command/issues/123

**Comment by schlessera** [comment]
Release completed. Great work, all!
