### ISSUE TITLE
WP-CLI v1.5.1 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4766]
There are several bugs worth bundling into a v1.5.1 release:

* [x] Cannot install package from private repo https://github.com/wp-cli/package-command/issues/76
* [x] Placeholder escaping problem with `$[0-9]` present in values https://github.com/wp-cli/wp-config-transformer/issues/2
* [x] String not found in serialized object https://github.com/wp-cli/search-replace-command/issues/68
* [x] Fix potential endless loop in prompt() https://github.com/wp-cli/php-cli-tools/pull/129
* [x] `wp cap list` output does not reflect grant https://github.com/wp-cli/role-command/issues/18
* [x] Soft changes need to be more flexible https://github.com/wp-cli/checksum-command/issues/34
* [x] `wp scaffold block` using `--theme` outputs the wrong code https://github.com/wp-cli/scaffold-command/issues/127
* [x] Should check for PCRE error on `preg_replace()` https://github.com/wp-cli/search-replace-command/issues/65

**Comment by danielbachhuber** [comment]
@schlessera Did you follow all [documented release steps](https://make.wordpress.org/cli/handbook/release-checklist/)?

**Comment by danielbachhuber** [comment]
> What I didn't yet do is update the handbook, as I'm not sure how this can be done to only cover 1.5.1.

I'm not sure I follow. Can you clarify?

> Other than that, everything should be taken care of already.

I still see:

* [ ] [Debian and RPM builds need to be generated](https://make.wordpress.org/cli/handbook/release-checklist/#updating-the-debian-and-rpm-builds).
* [ ] Update current stable version on the WP-CLI homepage and roadmap pages.
* [ ] Close the [v1.5.1 milestone](https://github.com/wp-cli/wp-cli/milestone/56).

**Comment by danielbachhuber** [comment]
> Sorry if this isn't an appropriate place to ask (happy to re-file elsewhere), but was it intentional for `1.5.1` to not include `wp-cli-1.5.1.phar.gpg`?

Sorry about that. I've signed and uploaded.

**Comment by schlessera** [comment]
@danielbachhuber:
Oh, I assumed the Debian and RPM builds would be triggered automatically. I'll go through your list.

**Comment by danielbachhuber** [comment]
@schlessera Is there a reason this issue is still open?

**Comment by schlessera** [comment]
Yes, the RPM & DEB builds haven't been completed yet. I had trouble with Travis last time I wanted to do that, and went down a rabbit hole (trouble which is still not resolved, unfortunately).

I'll try triggering the builds.
