### ISSUE TITLE
Adapt tests for addition of "Privacy Policy" page

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4775]
Core trunk has added a new default page that comes pre-installed as of [Changeset 42981](https://core.trac.wordpress.org/changeset/42981).

This innocuous change breaks multiple tests across many commands, as any counts that are done on `wp_posts` are suddenly of.

This is issue is meant to coordinate the effort to get all tests in check again.

* [x] wp-cli/cache-command :white_check_mark:
* [x] wp-cli/checksum-command :white_check_mark:
* [x] wp-cli/config-command :white_check_mark:
* [x] wp-cli/core-command :white_check_mark:
* [x] wp-cli/cron-command :white_check_mark:
* [x] wp-cli/db-command [[#97](https://github.com/wp-cli/db-command/issues/97)]
* [x] wp-cli/embed-command :white_check_mark:
* [x] wp-cli/entity-command [[#176](https://github.com/wp-cli/entity-command/issues/176)]
* [x] wp-cli/eval-command :white_check_mark:
* [x] wp-cli/export-command [[#35](https://github.com/wp-cli/export-command/issues/35)]
* [x] wp-cli/extension-command :white_check_mark:
* [x] wp-cli/import-command [[#24](https://github.com/wp-cli/import-command/issues/24)]
* [x] wp-cli/language-command :white_check_mark:
* [x] wp-cli/media-command :white_check_mark:
* [x] wp-cli/package-command :white_check_mark:
* [x] wp-cli/rewrite-command :white_check_mark:
* [x] wp-cli/role-command :white_check_mark:
* [x] wp-cli/scaffold-command :white_check_mark:
* [x] wp-cli/search-replace-command [[#77](https://github.com/wp-cli/search-replace-command/issues/77)]
* [x] wp-cli/server-command :white_check_mark:
* [x] wp-cli/shell-command :white_check_mark:
* [x] wp-cli/super-admin-command :white_check_mark:
* [x] wp-cli/widget-command :white_check_mark:

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/automated-tests/pull/21
