### ISSUE TITLE
Preparation for Release v2.2.0

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5192]
- [x] Tests break on WP `trunk` - `ls: cannot access - no such file or folder` [[language-command#81](https://github.com/wp-cli/language-command/issues/81)]
- [x] Adopt `WP_CLI_CS` across the `wp-cli` organization [[wp-cli#5179](https://github.com/wp-cli/wp-cli/issues/5179)]
- [x] Tests in PHP 7.3 fail because of a misuse of `compact()` [[core-command#113](https://github.com/wp-cli/core-command/issues/113)]
- [x] Test failure on WP 3.7.11 - Invalid Sidebar [[widget-command#31](https://github.com/wp-cli/widget-command/issues/31)]
- [x] Test failure on WP trunk - Invalid Sidebar [[widget-command#32](https://github.com/wp-cli/widget-command/issues/32)]
- [x] Test failure on Core trunk because of `download_package` signature change [[#119](https://github.com/wp-cli/core-command/issues/119)]
- [x] Command override don't work correctly [[#5202](https://github.com/wp-cli/wp-cli/issues/5202)]
