### ISSUE TITLE
Release checklist for v2.9.0

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/wp-cli#5843]
# Regular Release Checklist - v2.9.0

### Preparation

- [x] Draft release post on the [make.wordpress.org CLI blog](https://make.wordpress.org/cli/wp-admin/post-new.php)
- [x] Regenerate command and internal API docs

    Command and internal API docs need to be regenerated before every major release, because they're meant to correlate with the release.

    ```
    git clone git@github.com:wp-cli/handbook.git
    cd handbook
    WP_CLI_PACKAGES_DIR=bin/packages ../wp-cli-bundle/vendor/bin/wp handbook gen-all
    ```

- [x] Verify results of [automated test suite](https://github.com/wp-cli/automated-tests)

### Updating WP-CLI

- [x] Create a branch called `release-x-x-x` on `wp-cli/wp-cli-bundle` to prepare the release PR.

- [x] Ensure that the contents of [VERSION](https://github.com/wp-cli/wp-cli/blob/master/VERSION) in `wp-cli/wp-cli` are changed to latest.

- [x] Update the WP-CLI version mention in `wp-cli/wp-cli`'s `README.md` ([ref](https://github.com/wp-cli/wp-cli/issues/3647)).

- [x] Lock `php-cli-tools` version (if needed)

    `php-cli-tools` is sometimes set to `dev-master` during the development cycle. During the WP-CLI release process, `composer.json` should be locked to a specific version. `php-cli-tools` may need a new version tagged as well.

- [x] Lock the framework version in the ([bundle repository](https://github.com/wp-cli/wp-cli-bundle/))

    The version constraint of the `wp-cli/wp-cli` framework requirement is usually set to `"dev-master"`. Set it to the stable tagged release that represents the version to be published.

    As an example, if releasing version 2.1.0 of WP-CLI, the `wp-cli/wp-cli-bundle` should require `"wp-cli/wp-cli": "^2.1.0"`.

### Updating the contributor list

- [x] Fetch the list of contributors (from within the [`wp-cli/wp-cli-dev`](https://githubcom/wp-cli/wp-cli-dev/) project repo)

    From within the `wp-cli/wp-cli-dev` project repo, use `wp maintenance contrib-list` to generate a list of release contributors:

    ```
    GITHUB_TOKEN=<token> wp maintenance contrib-list --format=markdown
    ```

    This script identifies pull request creators from `wp-cli/wp-cli-bundle`, `wp-cli/wp-cli`, `wp-cli/handbook`, and all bundled WP-CLI commands (e.g. `wp-cli/*-command`).

    For `wp-cli/wp-cli-bundle`, `wp-cli/wp-cli` and `wp-cli/handbook`, the script uses the currently open release milestone.

    For all bundled WP-CLI commands, the script uses all closed milestones since the last WP-CLI release (as identified by the version present in the `composer.lock` file). If a command was newly bundled since last release, contributors to that command will need to be manually added to the list.

    The script will also produce a total contributor and pull request count you can use in the release post.

### Updating the Phar build

- [x] Create a PR from the `release-x-x-x` branch in `wp-cli/wp-cli-bundle` and merge it. This will trigger the `wp-cli-release.*` builds.

- [x] Create a git tag and push it.

- [x] Create a stable [Phar build](https://github.com/wp-cli/builds/tree/gh-pages/phar):

    ```
    cd wp-cli/builds/phar
    cp wp-cli-release.phar wp-cli.phar
    md5 -q wp-cli.phar > wp-cli.phar.md5
    shasum -a 512 wp-cli.phar | cut -d ' ' -f 1 > wp-cli.phar.sha512
    ```

- [x] Sign the release with GPG (see <https://github.com/wp-cli/wp-cli/issues/2121>):

    ```
    gpg --output wp-cli.phar.gpg --default-key releases@wp-cli.org --sign wp-cli.phar
    gpg --output wp-cli.phar.asc --default-key releases@wp-cli.org --detach-sig --armor wp-cli.phar
    ```

    Note: The GPG key for `releases@wp-cli.org` has to be shared amongst maintainers.

- [x] Perform one last sanity check on the Phar by ensuring it displays its information

    ```
    php wp-cli.phar --info
    ```

- [x] Commit the Phar and its hashes to the builds repo

    ```
    git status
    git add .
    git commit -m "Update stable to v1.x.0"
    ```

- [x] Create a release on Github: <https://github.com/wp-cli/wp-cli/releases>. Make sure to upload the Phar from the builds directory.

    ```
    cp wp-cli.phar wp-cli-1.x.0.phar
    cp wp-cli.phar.gpg wp-cli-1.x.0.phar.gpg
    cp wp-cli.phar.asc wp-cli-1.x.0.phar.asc
    cp wp-cli.phar.md5 wp-cli-1.x.0.phar.md5
    cp wp-cli.phar.sha512 wp-cli-1.x.0.phar.sha512
    ```

- [x] Verify Phar release artifact

    ```
    $ wp cli update
    You have version 1.4.0-alpha-88450b8. Would you like to update to 1.4.0? [y/n] y
    Downloading from https://github.com/wp-cli/wp-cli/releases/download/v1.4.0/wp-cli-1.4.0.phar...
    md5 hash verified: 179fc8dacbfe3ebc2d00ba57a333c982
    New version works. Proceeding to replace.
    Success: Updated WP-CLI to 1.4.0.
    $ wp @daniel option get home
    https://danielbachhuber.com
    ```

### Updating the Debian and RPM builds

- [x] Trigger Travis CI build on [wp-cli/deb-build](https://github.com/wp-cli/deb-build)
- [x] Trigger Travis CI build on [wp-cli/rpm-build](https://github.com/wp-cli/rpm-build)

    The two builds shouldn't be triggered at the same time, as one of them will then fail to push its build artifact due to the remote not being in the same state anymore.

    Due to aggressive caching by the GitHub servers, the scripts might pull in cached version of the previous release instead of the new one. This seems to resolve automatically in a period of 24 hours.

### Updating the Homebrew formula (should happen automatically)

- [x] Update the url and sha256 here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/wp-cli.rb#L4-L5

    The easiest way to do so is by using the following command:

    ```
    brew bump-formula-pr --strict wp-cli --url=https://github.com/wp-cli/wp-cli/releases/download/v2.x.0/wp-cli-2.x.0.phar --sha256=$(wget -qO- https://github.com/wp-cli/wp-cli/releases/download/v2.x.0/wp-cli-2.x.0.phar - | sha256sum | cut -d " " -f 1)
    ```

### Updating the website

- [x] Verify <https://github.com/wp-cli/wp-cli.github.com#readme> is up-to-date

- [x] Update the [roadmap](https://make.wordpress.org/cli/handbook/roadmap/)

- [x] Update all version references on the homepage (and localized homepages).

- [x] Tag a release of the website

### Announcing

- [x] Announce release on the [WP-CLI Twitter account](https://twitter.com/wpcli)
- [ ] Announce using the `/announce` slash command in the [`#cli`](https://wordpress.slack.com/messages/C02RP4T41) Slack room.

### Bumping WP-CLI version again

- [x] Bump [VERSION](https://github.com/wp-cli/wp-cli/blob/master/VERSION) in [`wp-cli/wp-cli`](https://github.com/wp-cli/wp-cli) again.

    For instance, if the release version was `0.24.0`, the version should be bumped to `0.25.0-alpha`. Doing so ensure `wp cli update --nightly` works as expected.

- [x] Change the version constraint on `"wp-cli/wp-cli"` in `wp-cli/wp-cli-bundle`'s [`composer.json`](https://github.com/wp-cli/wp-cli-bundle/blob/master/composer.json) file back to `"dev-master"`.

- [x] Adapt the branch alias in `wp-cli/wp-cli`'s [`composer.json`](https://github.com/wp-cli/wp-cli/blob/master/composer.json) file to match the new alpha version.

**Comment by swissspidy** [comment]
> * Regenerate command and internal API docs

* https://github.com/wp-cli/handbook/pull/467

**Comment by swissspidy** [comment]
Here are the release notes, generated via `GITHUB_TOKEN=<token> wp maintenance release-notes`

<details>
<summary>Release notes</summary>

```md

#### [wp-cli/wp-cli-bundle](https://github.com/wp-cli/wp-cli-bundle/)

- Update Composer lock file [[#584](https://github.com/wp-cli/wp-cli-bundle/pull/584)]
- Update Composer lock file [[#579](https://github.com/wp-cli/wp-cli-bundle/pull/579)]
- Update Composer dependencies (2023-10-02) [[#578](https://github.com/wp-cli/wp-cli-bundle/pull/578)]
- Update Composer dependencies (2023-09-19) [[#576](https://github.com/wp-cli/wp-cli-bundle/pull/576)]
- Bump wp-cli/entity-command from 2.5.3 to 2.5.4 [[#575](https://github.com/wp-cli/wp-cli-bundle/pull/575)]
- Bump wp-cli/export-command from 2.1.1 to 2.1.12 [[#574](https://github.com/wp-cli/wp-cli-bundle/pull/574)]
- Update `wp-cli/wp-cli` to db3d01f [[#573](https://github.com/wp-cli/wp-cli-bundle/pull/573)]
- Bump actions/checkout from 3 to 4 [[#572](https://github.com/wp-cli/wp-cli-bundle/pull/572)]
- Bump wp-cli/media-command from 2.0.18 to 2.0.19 [[#570](https://github.com/wp-cli/wp-cli-bundle/pull/570)]
- Update to WPCS v3 [[#569](https://github.com/wp-cli/wp-cli-bundle/pull/569)]
- No longer necessary to test WordPress latest with PHP 5.6 [[#568](https://github.com/wp-cli/wp-cli-bundle/pull/568)]
- Update `composer.lock` (2023-08-17) [[#566](https://github.com/wp-cli/wp-cli-bundle/pull/566)]
- Update branch name in wp-cli-updatedeb.sh [[#565](https://github.com/wp-cli/wp-cli-bundle/pull/565)]
- Update composer.lock (2023-08-04) [[#564](https://github.com/wp-cli/wp-cli-bundle/pull/564)]
- Update DEBIAN/control depends to support later versions of PHP [[#562](https://github.com/wp-cli/wp-cli-bundle/pull/562)]
- Update `composer.lock` (2023-07-13 v2) [[#561](https://github.com/wp-cli/wp-cli-bundle/pull/561)]
- Run `trunk` deploy tests against PHP 7 instead of PHP 5.6 [[#560](https://github.com/wp-cli/wp-cli-bundle/pull/560)]
- Update `composer.lock` (2023-07-13) [[#559](https://github.com/wp-cli/wp-cli-bundle/pull/559)]
- Update `composer.lock` to latest (2023-06-09) [[#557](https://github.com/wp-cli/wp-cli-bundle/pull/557)]
- Update Composer lock file [[#551](https://github.com/wp-cli/wp-cli-bundle/pull/551)]

#### [wp-cli/wp-cli](https://github.com/wp-cli/wp-cli/)

- Add debugging output for @when command registration [[#5841](https://github.com/wp-cli/wp-cli/pull/5841)]
- Fix `--skip-themes` for WordPress 6.4 [[#5840](https://github.com/wp-cli/wp-cli/pull/5840)]
- Update phpcs.xml to match new WPCS rules [[#5836](https://github.com/wp-cli/wp-cli/pull/5836)]
- Update to WPCS v3 [[#5834](https://github.com/wp-cli/wp-cli/pull/5834)]
- Respect alias `--path=` in `IncludeRequestsAutoloader` [[#5830](https://github.com/wp-cli/wp-cli/pull/5830)]
- Update type hint of $callable parameter in add_command() method [[#5828](https://github.com/wp-cli/wp-cli/pull/5828)]
- Require PHP 7.0 for tests installing WP via Composer [[#5825](https://github.com/wp-cli/wp-cli/pull/5825)]
- Require PHP 7+ for installing Gutenberg [[#5824](https://github.com/wp-cli/wp-cli/pull/5824)]
- Run test only on PHP 7.0+ [[#5823](https://github.com/wp-cli/wp-cli/pull/5823)]
- Display a custom error message when `themes/functions.php` fatals [[#5817](https://github.com/wp-cli/wp-cli/pull/5817)]
- Fix PHP 8.1 deprecation: ReturnTypeWillChange [[#5807](https://github.com/wp-cli/wp-cli/pull/5807)]
- Add support for the proxyjump key [[#5805](https://github.com/wp-cli/wp-cli/pull/5805)]
- Mention updating the homepage in the release process [[#5802](https://github.com/wp-cli/wp-cli/pull/5802)]
- Fix link in README.md [[#5801](https://github.com/wp-cli/wp-cli/pull/5801)]

#### [wp-cli/handbook](https://github.com/wp-cli/handbook/)

- Add documentation for `--context` [[#466](https://github.com/wp-cli/handbook/pull/466)]
- Remove blank line from HTML table [[#465](https://github.com/wp-cli/handbook/pull/465)]
- Add detailed documentation for --ssh [[#462](https://github.com/wp-cli/handbook/pull/462)]
- Add some issues for WCUS 2023 Contributor Day [[#460](https://github.com/wp-cli/handbook/pull/460)]
- Add Rad Web Hosting Provider [[#458](https://github.com/wp-cli/handbook/pull/458)]
- Fix handbook manifest JSON corruption [[#457](https://github.com/wp-cli/handbook/pull/457)]
- Add a new doc for WordCamp Contributor Day [[#456](https://github.com/wp-cli/handbook/pull/456)]
- Update plugin-unit-tests.md [[#455](https://github.com/wp-cli/handbook/pull/455)]
- Update GitHub links to use search endpoint instead [[#453](https://github.com/wp-cli/handbook/pull/453)]
- Fix multisite search-replace example [[#451](https://github.com/wp-cli/handbook/pull/451)]
- Adds example --ssh= schemes [[#450](https://github.com/wp-cli/handbook/pull/450)]
- Adds common issue for xdebug max nesting errors. [[#449](https://github.com/wp-cli/handbook/pull/449)]
- Add more subheadings to Functional Tests [[#448](https://github.com/wp-cli/handbook/pull/448)]
- Added "Sort plugins or themes by certain column(s)" to "Snippets" [[#446](https://github.com/wp-cli/handbook/pull/446)]

#### [wp-cli/wp-cli.github.com](https://github.com/wp-cli/wp-cli.github.com/)

- Update translations [[#434](https://github.com/wp-cli/wp-cli.github.com/pull/434)]
- fix link in `index.md` [[#433](https://github.com/wp-cli/wp-cli.github.com/pull/433)]
- update ja/index.md [[#432](https://github.com/wp-cli/wp-cli.github.com/pull/432)]

#### [wp-cli/cache-command](https://github.com/wp-cli/cache-command/)

- Update to WPCS v3 [[#91](https://github.com/wp-cli/cache-command/pull/91)]
- Add `phpcbf` Composer script [[#90](https://github.com/wp-cli/cache-command/pull/90)]
- Update warning text during multisite cache flushes [[#88](https://github.com/wp-cli/cache-command/pull/88)]


#### [wp-cli/checksum-command](https://github.com/wp-cli/checksum-command/)

- Don't warn about a `.maintenance` file in the root directory [[#114](https://github.com/wp-cli/checksum-command/pull/114)]
- Regenerate README file [[#113](https://github.com/wp-cli/checksum-command/pull/113)]
- Add an `--exclude=<plugin>` argument to `wp plugin verify-checksums` [[#104](https://github.com/wp-cli/checksum-command/pull/104)]


- Update to WPCS v3 [[#116](https://github.com/wp-cli/checksum-command/pull/116)]
- Only run tests on PHP 7.0+ [[#115](https://github.com/wp-cli/checksum-command/pull/115)]


#### [wp-cli/config-command](https://github.com/wp-cli/config-command/)

- Change mysql CLI call to native PHP function [[#158](https://github.com/wp-cli/config-command/pull/158)]


- Update to WPCS v3 [[#163](https://github.com/wp-cli/config-command/pull/163)]
- Slight tweaks to `wp config is-true` [[#162](https://github.com/wp-cli/config-command/pull/162)]
- Add `wp config is-true` command [[#161](https://github.com/wp-cli/config-command/pull/161)]


- Fail on empty table prefix [[#164](https://github.com/wp-cli/config-command/pull/164)]


#### [wp-cli/core-command](https://github.com/wp-cli/core-command/)

- Tests: Fix tests referencing trunk/nightly [[#238](https://github.com/wp-cli/core-command/pull/238)]
- Improve documentation for core is-installed command [[#237](https://github.com/wp-cli/core-command/pull/237)]


- Update to WPCS v3 [[#241](https://github.com/wp-cli/core-command/pull/241)]
- Only run tests on PHP 7.0+ [[#239](https://github.com/wp-cli/core-command/pull/239)]
- Directly pass empty or missing password parameter to WordPress [[#232](https://github.com/wp-cli/core-command/pull/232)]


#### [wp-cli/cron-command](https://github.com/wp-cli/cron-command/)

- Update to WPCS v3 [[#100](https://github.com/wp-cli/cron-command/pull/100)]
- Fix incorrect recurrence display for events with invalid schedules [[#99](https://github.com/wp-cli/cron-command/pull/99)]


#### [wp-cli/db-command](https://github.com/wp-cli/db-command/)

- Update to WPCS v3 [[#240](https://github.com/wp-cli/db-command/pull/240)]


#### [wp-cli/embed-command](https://github.com/wp-cli/embed-command/)

- Replace asciinema.org in tests [[#71](https://github.com/wp-cli/embed-command/pull/71)]


* Fix tests [#72]

- Update to WPCS v3 [[#73](https://github.com/wp-cli/embed-command/pull/73)]


#### [wp-cli/entity-command](https://github.com/wp-cli/entity-command/)

- Regenerate README file [[#410](https://github.com/wp-cli/entity-command/pull/410)]
- User: Add more examples for scoped password reset [[#409](https://github.com/wp-cli/entity-command/pull/409)]
- Warn when deleting multisite user with no blog roles [[#408](https://github.com/wp-cli/entity-command/pull/408)]


- PHP 8.2 Deprecation: Fix creation of dynamic property. [[#413](https://github.com/wp-cli/entity-command/pull/413)]


- Regenerate README file [[#424](https://github.com/wp-cli/entity-command/pull/424)]
- Fix typo for `$parent_instance` param in `RecursiveDataStructureTraverser` constructor [[#422](https://github.com/wp-cli/entity-command/pull/422)]
- Update to WPCS v3 [[#419](https://github.com/wp-cli/entity-command/pull/419)]
- Prevent unexpected missed schedules when generating new posts [[#418](https://github.com/wp-cli/entity-command/pull/418)]
- Add `--slug=<site>` as an available parameter to `wp site` commands [[#416](https://github.com/wp-cli/entity-command/pull/416)]
- Fix incorrect 'its' in the documentation [[#414](https://github.com/wp-cli/entity-command/pull/414)]


- Increase precision of `wp post generate` test [[#425](https://github.com/wp-cli/entity-command/pull/425)]


- Add test case for publishing post and updating date behavior [[#428](https://github.com/wp-cli/entity-command/pull/428)]


#### [wp-cli/eval-command](https://github.com/wp-cli/eval-command/)

- Regenerate README file [[#69](https://github.com/wp-cli/eval-command/pull/69)]
- Minor documentation tweaks to `wp eval-file` [[#68](https://github.com/wp-cli/eval-command/pull/68)]


- Update to WPCS v3 [[#71](https://github.com/wp-cli/eval-command/pull/71)]


#### [wp-cli/export-command](https://github.com/wp-cli/export-command/)

- Update to WPCS v3 [[#110](https://github.com/wp-cli/export-command/pull/110)]
- Allow orphan terms to be exported with `--allow_orphan_terms` flag [[#109](https://github.com/wp-cli/export-command/pull/109)]


#### [wp-cli/extension-command](https://github.com/wp-cli/extension-command/)

- Update to WPCS v3 [[#373](https://github.com/wp-cli/extension-command/pull/373)]
- Add optional 'author' field to `wp plugin list` [[#369](https://github.com/wp-cli/extension-command/pull/369)]
- Default to false when the "network" flag is omitted in the activate command [[#364](https://github.com/wp-cli/extension-command/pull/364)]


- Warn on delete failure, instead of hard exiting [[#376](https://github.com/wp-cli/extension-command/pull/376)]


#### [wp-cli/i18n-command](https://github.com/wp-cli/i18n-command/)

- Update to WPCS v3 [[#367](https://github.com/wp-cli/i18n-command/pull/367)]


#### [wp-cli/import-command](https://github.com/wp-cli/import-command/)

- Update to WPCS v3 [[#84](https://github.com/wp-cli/import-command/pull/84)]


#### [wp-cli/language-command](https://github.com/wp-cli/language-command/)

- Add `wp plugin language uninstall --all` [[#128](https://github.com/wp-cli/language-command/pull/128)]
- Update to WPCS v3 [[#126](https://github.com/wp-cli/language-command/pull/126)]
- Add deprecation hint in `wp language core activate`'s docblock [[#125](https://github.com/wp-cli/language-command/pull/125)]
- Support `wp language theme uninstall --all` [[#124](https://github.com/wp-cli/language-command/pull/124)]


#### [wp-cli/maintenance-mode-command](https://github.com/wp-cli/maintenance-mode-command/)

- Update to WPCS v3 [[#26](https://github.com/wp-cli/maintenance-mode-command/pull/26)]


#### [wp-cli/media-command](https://github.com/wp-cli/media-command/)

- Remove `trunk` from this scenario [[#179](https://github.com/wp-cli/media-command/pull/179)]


- Replace usage of `via.placeholder.com` [[#183](https://github.com/wp-cli/media-command/pull/183)]
- Add support for 'url' to `--porcelain` to output the URL instead of attachment ID [[#182](https://github.com/wp-cli/media-command/pull/182)]
- Fix legacy test by running against WP versions when PHP matches [[#181](https://github.com/wp-cli/media-command/pull/181)]

- Update to WPCS v3 [[#184](https://github.com/wp-cli/media-command/pull/184)]


#### [wp-cli/package-command](https://github.com/wp-cli/package-command/)

- Update to WPCS v3 [[#178](https://github.com/wp-cli/package-command/pull/178)]
- Document support for GitHub token authentication [[#177](https://github.com/wp-cli/package-command/pull/177)]
- Use auth for GitLab private repos, and fix GitLab failover behavior [[#157](https://github.com/wp-cli/package-command/pull/157)]


#### [wp-cli/php-cli-tools](https://github.com/wp-cli/php-cli-tools/)

- Prevent warnings in PHP 8.2 when `$col_values` is empty [[#160](https://github.com/wp-cli/php-cli-tools/pull/160)]


- Update to WPCS v3 [[#161](https://github.com/wp-cli/php-cli-tools/pull/161)]


- PHP 8.2: strwidth() & Colors::pad()/decolorize() should always work with a string [[#163](https://github.com/wp-cli/php-cli-tools/pull/163)]


#### [wp-cli/rewrite-command](https://github.com/wp-cli/rewrite-command/)

- Update to WPCS v3 [[#63](https://github.com/wp-cli/rewrite-command/pull/63)]


#### [wp-cli/role-command](https://github.com/wp-cli/role-command/)

- Update to WPCS v3 [[#60](https://github.com/wp-cli/role-command/pull/60)]


#### [wp-cli/scaffold-command](https://github.com/wp-cli/scaffold-command/)

- Only install trunk on PHP 7.0+ [[#321](https://github.com/wp-cli/scaffold-command/pull/321)]


- Update to WPCS v3 [[#324](https://github.com/wp-cli/scaffold-command/pull/324)]
- Run test only on PHP 7.0+ [[#323](https://github.com/wp-cli/scaffold-command/pull/323)]


#### [wp-cli/search-replace-command](https://github.com/wp-cli/search-replace-command/)

- Adjust string to avoid conflict with something in trunk [[#185](https://github.com/wp-cli/search-replace-command/pull/185)]


- Update to WPCS v3 [[#188](https://github.com/wp-cli/search-replace-command/pull/188)]
- Fix production multisite database transformation example [[#187](https://github.com/wp-cli/search-replace-command/pull/187)]


#### [wp-cli/server-command](https://github.com/wp-cli/server-command/)

- Update to WPCS v3 [[#80](https://github.com/wp-cli/server-command/pull/80)]


#### [wp-cli/shell-command](https://github.com/wp-cli/shell-command/)

- Update to WPCS v3 [[#64](https://github.com/wp-cli/shell-command/pull/64)]


#### [wp-cli/super-admin-command](https://github.com/wp-cli/super-admin-command/)

- Update to WPCS v3 [[#54](https://github.com/wp-cli/super-admin-command/pull/54)]


#### [wp-cli/widget-command](https://github.com/wp-cli/widget-command/)

- Update to WPCS v3 [[#60](https://github.com/wp-cli/widget-command/pull/60)]


#### [wp-cli/wp-config-transformer](https://github.com/wp-cli/wp-config-transformer/)

- Update to WPCS v3 [[#46](https://github.com/wp-cli/wp-config-transformer/pull/46)]

```

</details>

Note, the following warnings were printed during generation:

```
Warning: Release notes not found for wp-cli/wp-cli-bundle@v2.9.0, falling back to pull-request source
Warning: Release notes not found for wp-cli/wp-cli@v2.9.0, falling back to pull-request source
Warning: Release notes not found for wp-cli/handbook@v2.9.0, falling back to pull-request source
Warning: Release notes not found for wp-cli/wp-cli.github.com@v2.9.0, falling back to pull-request source
PHP Deprecated:  version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in /wp-cli-dev/.maintenance/src/Release_Notes_Command.php on line 118
```

-----

Next up, contribution list, generated via Here are the release notes, generated via `GITHUB_TOKEN=<token> wp maintenance contrib-list --format=markdown`

<details>
<summary>Contribution list</summary>

```md
Current open wp-cli/wp-cli milestone: 2.9.0
 - Contributors: 8
 - Pull requests: 14

Closed wp-cli/cache-command milestone(s): 2.1.1
 - Contributors: 3
 - Pull requests: 3
Closed wp-cli/checksum-command milestone(s): 2.2.3, 2.2.4
 - Contributors: 3
 - Pull requests: 3
 - Contributors: 2
 - Pull requests: 2
Closed wp-cli/config-command milestone(s): 2.2.0, 2.3.0, 2.3.1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 3
 - Pull requests: 3
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/core-command milestone(s): 2.1.14, 2.1.15
 - Contributors: 2
 - Pull requests: 2
 - Contributors: 3
 - Pull requests: 3
Closed wp-cli/cron-command milestone(s): 2.2.3
 - Contributors: 2
 - Pull requests: 2
Closed wp-cli/db-command milestone(s): 2.0.26
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/embed-command milestone(s): 2.0.13, 2.0.14, 2.0.15
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/entity-command milestone(s): 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6
 - Contributors: 3
 - Pull requests: 3
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 6
 - Pull requests: 6
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/eval-command milestone(s): 2.2.3, 2.2.4
 - Contributors: 2
 - Pull requests: 2
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/export-command milestone(s): 2.1.12
 - Contributors: 2
 - Pull requests: 2
Closed wp-cli/extension-command milestone(s): 2.1.14, 2.1.15
 - Contributors: 3
 - Pull requests: 3
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/i18n-command milestone(s): 2.4.4
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/i18n-command milestone(s): 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4
 - Contributors: 6
 - Pull requests: 23
 - Contributors: 2
 - Pull requests: 2
 - Contributors: 4
 - Pull requests: 11
 - Contributors: 1
 - Pull requests: 2
 - Contributors: 2
 - Pull requests: 4
 - Contributors: 5
 - Pull requests: 19
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 5
 - Pull requests: 5
 - Contributors: 2
 - Pull requests: 4
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 5
 - Pull requests: 7
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 4
 - Pull requests: 5
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 5
 - Pull requests: 17
 - Contributors: 2
 - Pull requests: 2
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 4
 - Pull requests: 6
 - Contributors: 2
 - Pull requests: 9
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 2
 - Pull requests: 4
 - Contributors: 3
 - Pull requests: 3
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/import-command milestone(s): 2.0.12
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/language-command milestone(s): 2.0.16
 - Contributors: 4
 - Pull requests: 4
Closed wp-cli/maintenance-mode-command milestone(s): 2.0.10
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/media-command milestone(s): 2.0.18, 2.0.19, 2.0.20
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 3
 - Pull requests: 3
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/package-command milestone(s): 2.4.0
 - Contributors: 3
 - Pull requests: 3
Closed wp-cli/php-cli-tools milestone(s): 0.11.19, 0.11.20, 0.11.21
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/rewrite-command milestone(s): 2.0.13
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/role-command milestone(s): 2.0.14
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/scaffold-command milestone(s): 2.1.2, 2.1.3
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 2
 - Pull requests: 2
Closed wp-cli/search-replace-command milestone(s): 2.1.2, 2.1.3
 - Contributors: 1
 - Pull requests: 1
 - Contributors: 2
 - Pull requests: 2
Closed wp-cli/server-command milestone(s): 2.0.13
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/shell-command milestone(s): 2.0.14
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/super-admin-command milestone(s): 2.0.12
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/widget-command milestone(s): 2.1.9
 - Contributors: 1
 - Pull requests: 1
Closed wp-cli/wp-config-transformer milestone(s): 1.3.4
 - Contributors: 1
 - Pull requests: 1
Total contributors: 62
Total pull requests: 224
[@Ancocodet](https://github.com/Ancocodet), [@atoomic](https://github.com/atoomic), [@benjaminprojas](https://github.com/benjaminprojas), [@chesio](https://github.com/chesio), [@cliffordp](https://github.com/cliffordp), [@connerbw](https://github.com/connerbw), [@danielbachhuber](https://github.com/danielbachhuber), [@dd32](https://github.com/dd32), [@dlind1](https://github.com/dlind1), [@drzraf](https://github.com/drzraf), [@elenachavdarova](https://github.com/elenachavdarova), [@fmfernandes](https://github.com/fmfernandes), [@GaryJones](https://github.com/GaryJones), [@gedex](https://github.com/gedex), [@github-actions[bot]](https://github.com/apps/github-actions), [@gitlost](https://github.com/gitlost), [@greatislander](https://github.com/greatislander), [@herregroen](https://github.com/herregroen), [@jacksonwp](https://github.com/jacksonwp), [@janw-me](https://github.com/janw-me), [@jenkoian](https://github.com/jenkoian), [@jrfnl](https://github.com/jrfnl), [@justinmaurerdotdev](https://github.com/justinmaurerdotdev), [@l3ku](https://github.com/l3ku), [@localheinz](https://github.com/localheinz), [@MannyAdumbire](https://github.com/MannyAdumbire), [@matzeeable](https://github.com/matzeeable), [@michaelzangl](https://github.com/michaelzangl), [@MiguelAxcar](https://github.com/MiguelAxcar), [@mrsdizzie](https://github.com/mrsdizzie), [@NielsdeBlaauw](https://github.com/NielsdeBlaauw), [@oandregal](https://github.com/oandregal), [@ocean90](https://github.com/ocean90), [@Pathan-Amaankhan](https://github.com/Pathan-Amaankhan), [@paulschreiber](https://github.com/paulschreiber), [@pbiron](https://github.com/pbiron), [@pdaalder](https://github.com/pdaalder), [@petertwise](https://github.com/petertwise), [@petitphp](https://github.com/petitphp), [@pmbaldha](https://github.com/pmbaldha), [@ponsfrilus](https://github.com/ponsfrilus), [@rafaelzaleski](https://github.com/rafaelzaleski), [@raicem](https://github.com/raicem), [@rodrigoprimo](https://github.com/rodrigoprimo), [@rwagner00](https://github.com/rwagner00), [@schlessera](https://github.com/schlessera), [@shendy-a8c](https://github.com/shendy-a8c), [@siliconforks](https://github.com/siliconforks), [@slaFFik](https://github.com/slaFFik), [@Soean](https://github.com/Soean), [@Souptik2001](https://github.com/Souptik2001), [@spicecadet](https://github.com/spicecadet), [@stoyan-g](https://github.com/stoyan-g), [@strarsis](https://github.com/strarsis), [@swissspidy](https://github.com/swissspidy), [@tubiz](https://github.com/tubiz), [@Tug](https://github.com/Tug), [@wojsmol](https://github.com/wojsmol), [@wojtekn](https://github.com/wojtekn), [@WPprodigy](https://github.com/WPprodigy), [@yousan](https://github.com/yousan), [@zzap](https://github.com/zzap)
```

</details>


Note, the following warnings were printed during generation:

```
PHP Deprecated:  version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in /wp-cli-dev/.maintenance/src/Contrib_List_Command.php on line 126
```

**Comment by swissspidy** [comment]
Version bump PR for `wp-cli/wp-cli`:

* https://github.com/wp-cli/wp-cli/pull/5846

**Comment by szepeviktor** [comment]
WP-CLI stubs will be released in a minute 💣
https://github.com/php-stubs/wp-cli-stubs
